name: Run Deployment Script

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Echo
        run: echo "Running Deployment Script"

      - name: Run Deployment Script
        run: bash ~/deploy.sh
