name: Run Deployment Script

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Echo
        run: echo "Running Deployment Script"

      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Run Deployment Script
        run: bash ./deploy.sh 
